AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: NestJS on AWS Lambda

Resources:
  CaterKartApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/serverless.handler
      Runtime: nodejs20.x
      CodeUri: ./
      MemorySize: 256
      Timeout: 20
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  CaterKartApi:
    Description: 'API Gateway endpoint URL for the CaterKart functions'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'